FROM node:22-alpine

WORKDIR /app

# Copiamos los archivos de dependencias a /app
COPY package.json ./

RUN npm install

# Copiamos el resto del código a /app
COPY . ./

RUN npm run build

EXPOSE 3000

# Sin la coma al final
CMD ["npm", "start"]